server:
  port: 8081

spring:
  application:
    name: leandro.cahuana
  data:
    mongodb:
      database: APIs
      uri: mongodb+srv://leandroCahuana:jRtrVG9NOl0PVv73@cluster01.6kpaarv.mongodb.net/?appName=Cluster01

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html