# kubectl apply -f leandro-cahuana-04-secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: leandro-cahuana-04-secret
  namespace: leandro-cahuana-04-namespace
type: Opaque
data:
  PORT: ODA4NQ==
  DATABASE_URL: bW9uZ29kYitzcnY6Ly9sZWFuZHJvQ2FodWFuYTpqUnRyVkc5Tk9sMFBWdjczQGNsdXN0ZXIwMS42a3BhYXJ2Lm1vbmdvZGIubmV0Lz9hcHBOYW1lPUNsdXN0ZXIwMQ==   # en Base64
  API_ONE_KEY: MmIzZjQ5MDY5NG1zaDZmYzkxYWI3MTZjMWE4NnAxZDM2N2Zqc24xY2I4Y2NhMTc3ZTU=
  API_ONE_HOST: c3BlZWNoLXRvLXRleHQtYWkucC5yYXBpZGFwaS5jb20=
  API_TWO_URI: aHR0cHM6Ly93aGF0c2FwcC1udW1iZXItdmFsaWRhdG9yMy5wLnJhcGlkYXBpLmNvbS9XaGF0c2FwcE51bWJlckhhc0l0V2l0aFRva2Vu
  API_TWO_KEY: MmIzZjQ5MDY5NG1zaDZmYzkxYWI3MTZjMWE4NnAxZDM2N2Zqc24xY2I4Y2NhMTc3ZTU=
  API_TWO_HOST: d2hhdHNhcHAtbnVtYmVyLXZhbGlkYXRvcjMucC5yYXBpZGFwaS5jb20=

# https://base64.guru/converter
# echo -n "demo123" | base64
# echo "ZGVtbzEyMw==" | base64 --decode